# Hypothetical Operating System Testbed (HOST) Dispatcher Shell
# Operating Systems Internal - Assignment 2
# author: Sebastian Kim

all:
	gcc -Wall -g hostd.c -o hostd
	gcc -Wall sigtrap.c -o process
	
clean:
	rm -rf *.o
	rm -rf hostd process 
